### ISSUE TITLE
Feat: Nesting Model Ref on Response

### ISSUE THREAD

**Issue by HasanAshab** [ad-on-is/adonis-autoswagger#64]
First of all, AutoSwagger is the most **active** 3rd party package of AdonisJs I have ever seen! It saved my lot of time :).

AutoSwagger has the feature to reference model on **@responseBody**
But some time we may need to put model deeper.

My usecase is to ref model inside **data** key
```typescript
/**
  @responseBody 201 - { "message": "Verification email sent", "data": <User> }
*/
```

Thanks in advance!

**Comment by ad-on-is** [comment]
Fixed in 3.3.0

**Comment by HasanAshab** [comment]
Still not working. Its giving unexpected output

Here is my method
```typescript
  /**
   * @register
   * @summary Register a new user
   * @requestFormDataBody { "email": { "type": "string" }, "username": { "type": "string" }, "password": { "type": "string" }, "avatar": { "type": "string", "format": "binary" }, "recaptchaResponse": { "type": "string" } }
   * @responseBody 201 - { "message": "Verification email sent", "data": <User> }
   * @responseHeader 201 - Location - URL of the registered user's profile
   */
  async register({ request, response }: HttpContext) {
 
```

And here is the generated body
```typescript
{
  "id": 939,
  "email": "johndoe@example.com"
}
```

**Comment by ad-on-is** [comment]
Can you try requestBody instead of requestformdatabody

**Comment by HasanAshab** [comment]
I just removed **@requestformdatabody** but still same result

**Comment by ad-on-is** [comment]
Oh and it also works with requestformdatabody

![image](https://github.com/ad-on-is/adonis-autoswagger/assets/9553253/6f5a294d-6018-436b-9e69-36e4ee189c97)

**Comment by HasanAshab** [comment]
Oh, sorry I forgot to add quote on <User>.
Now its working properly

**Comment by ad-on-is** [comment]
> Oh, sorry I forgot to add quote on . Now its working properly

Oh man, and I thought you were talking about the requestformdatabody 🤦🏻😅

**Comment by HasanAshab** [comment]
😅 thanks for your time
